require "colorize"
require "vala"

VALA_DIR = "c:/vala-0.20.1"
VALA_VAPI_DIR = "c:/ProgramData/vala-0.20/vapi"

PNAME = {
  service: "Service",
  service_app: "main.service"
}

namespace :compile do
  desc "Comile service dll"
  task :service do |task_name|
    Vala.profile_task(PNAME[:service], task_name) {
      sh Vala.new(
        application_type: "shared-library",
        project_name: PNAME[:service],
        project_dir: "./service",
        pkgs: "gio-2.0",
        files: FileList["./service/**/*.vala"]
      ).compile_s
    }
  end

  task :app do |task_name|
    Vala.profile_task(PNAME[])
  end
end

namespace :install do
  desc "Install service dll"
  task :service do |task_name|
    Vala.profile_task(PNAME[:service], task_name) {
      Vala.install_library(PNAME[:service], project_dir: "./service")
    }
  end
end

# namespace :install do 
#   task :system do |task_name|
#     Vala.profile_task(PNAME[:system], task_name.to_s) {
#       Vala.install_library PNAME[:system]
#     }
#   end
# end

# namespace :clean do
#   task :system do |task_name|
#     Vala.profile_task(PNAME[:system], task_name.to_s) {
#       rm_f("""
#         build/#{PNAME[:system]}.dll 
#         build/#{PNAME[:system]}.vapi 
#         build/#{PNAME[:system]}.h
#       """.split " ")
#     }
#   end
# end

# namespace :guard do
#   task :system => ["compile:system", "install:system"]
# end

task :default => ["compile:service", "install:service"]