require "colorize"
require "vala"

VALA_DIR = "c:/vala-0.20.1"
VALA_VAPI_DIR = "c:/ProgramData/vala-0.20/vapi"

PNAME = {
  service: "Service",
  service_app: "main.service"
}

namespace :compile do
  desc "Comile service dll"
  task :service do |task_name|
    Vala.profile_task(PNAME[:service], task_name) {
      system("#{Vala.new(
          application_type: "shared-library",
          project_name: PNAME[:service],
          project_dir: "./service",
          pkgs: "gio-2.0 gtk+-3.0",
          files: FileList["./service/**/*.vala"]
        ).compile_s}")
    }
  end

  task :app do |task_name|
    Vala.profile_task(PNAME[])
  end
end

namespace :install do
  desc "Install service dll"
  task :service do |task_name|
    Vala.profile_task(PNAME[:service], task_name) {
      Vala.install_library(PNAME[:service], project_dir: "./service")
    }
  end
end

task :test do
  a = `pkg-config --libs --cflags glib-2.0`
  a = `pkg-config --list-all`
  libs = a.lines.map { |x| x.split[0] }
  puts libs.include? "glib-2.0"
end
# task :default => ["compile:service", "install:service"]
task :default => [:test]