/* main.c generated by valac 0.20.1, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <System.h>

#define _g_free0(var) (var = (g_free (var), NULL))



gint _vala_main (gchar** args, int args_length1);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar** _tmp4_ = NULL;
	gchar** _tmp5_;
	gint _tmp5__length1;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar** _tmp12_ = NULL;
	gchar** _tmp13_;
	gint _tmp13__length1;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_;
	_tmp0_ = g_strdup ("valac");
	_tmp1_ = g_strdup ("./main.vala");
	_tmp2_ = g_strdup ("--ccode");
	_tmp3_ = g_strdup ("--pkg=System");
	_tmp4_ = g_new0 (gchar*, 4 + 1);
	_tmp4_[0] = _tmp0_;
	_tmp4_[1] = _tmp1_;
	_tmp4_[2] = _tmp2_;
	_tmp4_[3] = _tmp3_;
	_tmp5_ = _tmp4_;
	_tmp5__length1 = 4;
	_tmp6_ = system_utils_exec (_tmp5_, 4, "C:\\projects\\vala\\v\\vala-builder");
	_tmp7_ = _tmp6_;
	system_console_write_line (_tmp7_);
	_g_free0 (_tmp7_);
	_tmp5_ = (_vala_array_free (_tmp5_, _tmp5__length1, (GDestroyNotify) g_free), NULL);
	_tmp8_ = g_strdup ("pkg-config");
	_tmp9_ = g_strdup ("--libs");
	_tmp10_ = g_strdup ("--cflags");
	_tmp11_ = g_strdup ("glib-2.0");
	_tmp12_ = g_new0 (gchar*, 4 + 1);
	_tmp12_[0] = _tmp8_;
	_tmp12_[1] = _tmp9_;
	_tmp12_[2] = _tmp10_;
	_tmp12_[3] = _tmp11_;
	_tmp13_ = _tmp12_;
	_tmp13__length1 = 4;
	_tmp14_ = system_utils_get_current_dir ();
	_tmp15_ = _tmp14_;
	_tmp16_ = system_utils_exec (_tmp13_, 4, _tmp15_);
	_tmp17_ = _tmp16_;
	system_console_write_line (_tmp17_);
	_g_free0 (_tmp17_);
	_g_free0 (_tmp15_);
	_tmp13_ = (_vala_array_free (_tmp13_, _tmp13__length1, (GDestroyNotify) g_free), NULL);
	result = 0;
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return _vala_main (argv, argc);
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



