require "colorize"
require "vala"

VALA_DIR = "c:/vala-0.20.1"
VALA_VAPI_DIR = "c:/ProgramData/vala-0.20/vapi"

PNAME = {
  builder: "vala-builder"
}

vala = Vala.new(
  project_name: PNAME[:builder],
  pkgs: "System",
  files: FileList["./**/*.vala"]
)

task :compile do |task_name|
  Vala.profile_task(PNAME[:builder], task_name.to_s) {
    system vala.compile_s
  }
end

task :clean do |task_name|
  Vala.profile_task(PNAME[:builder], task_name.to_s) {
    rm_f FileList["build/**/*.*"]
  }
end

task :install do |task_name| 
  Vala.profile_task(PNAME[:builder], task_name.to_s) {
    vala.install_dependence
    # Vala.install_dep """
    #   glib
    #   gtk
    #   System
    # """
  }
end

task :run do |task_name|
  Vala.profile_task(PNAME[:builder], task_name.to_s) {
    `build/#{PNAME[:builder]}`
  }
end

task :builder => ["compile"]

task :default => [:compile]
