/* hello.c generated by valac 0.20.1, the Vala compiler
 * generated from hello.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdio.h>




void _vala_main (void);


void _vala_main (void) {
	FILE* _tmp0_;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "hello world\n");
}


int main (int argc, char ** argv) {
	g_type_init ();
	_vala_main ();
	return 0;
}



