/* Service.c generated by valac 0.20.1, the Vala compiler
 * generated from Service.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))



gint service_dll_main (void);
static guint8* _vala_array_dup1 (guint8* self, int length);


static guint8* string_get_data (const gchar* self, int* result_length1) {
	guint8* result;
	guint8* res;
	gint res_length1;
	gint _res_size_;
	gint _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	guint8* _tmp3_;
	gint _tmp3__length1;
	guint8* _tmp4_;
	gint _tmp4__length1;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = res_length1;
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	res_length1 = (gint) _tmp1_;
	_tmp2_ = res_length1;
	_tmp3_ = res;
	_tmp3__length1 = res_length1;
	_tmp4_ = _tmp3_;
	_tmp4__length1 = _tmp3__length1;
	if (result_length1) {
		*result_length1 = _tmp4__length1;
	}
	result = _tmp4_;
	return result;
}


static guint8* _vala_array_dup1 (guint8* self, int length) {
	return g_memdup (self, length * sizeof (guint8));
}


gint service_dll_main (void) {
	gint result = 0;
	GError * _inner_error_ = NULL;
	{
		GFile* _tmp0_ = NULL;
		GFile* file;
		GFile* _tmp1_;
		gboolean _tmp2_ = FALSE;
		GFile* _tmp4_;
		GFileOutputStream* _tmp5_ = NULL;
		GFileOutputStream* _tmp6_;
		GFileOutputStream* _tmp7_;
		GDataOutputStream* _tmp8_;
		GDataOutputStream* _tmp9_;
		GDataOutputStream* dos;
		GDataOutputStream* _tmp10_;
		gchar* _tmp11_;
		gchar* text;
		const gchar* _tmp12_;
		guint8* _tmp13_;
		gint _tmp13__length1;
		guint8* _tmp14_;
		gint _tmp14__length1;
		guint8* _tmp15_;
		gint _tmp15__length1;
		guint8* data;
		gint data_length1;
		gint _data_size_;
		glong written;
		_tmp0_ = g_file_new_for_path ("out.txt");
		file = _tmp0_;
		_tmp1_ = file;
		_tmp2_ = g_file_query_exists (_tmp1_, NULL);
		if (_tmp2_) {
			GFile* _tmp3_;
			_tmp3_ = file;
			g_file_delete (_tmp3_, NULL, &_inner_error_);
			if (_inner_error_ != NULL) {
				_g_object_unref0 (file);
				goto __catch0_g_error;
			}
		}
		_tmp4_ = file;
		_tmp5_ = g_file_create (_tmp4_, G_FILE_CREATE_REPLACE_DESTINATION, NULL, &_inner_error_);
		_tmp6_ = _tmp5_;
		if (_inner_error_ != NULL) {
			_g_object_unref0 (file);
			goto __catch0_g_error;
		}
		_tmp7_ = _tmp6_;
		_tmp8_ = g_data_output_stream_new ((GOutputStream*) _tmp7_);
		_tmp9_ = _tmp8_;
		_g_object_unref0 (_tmp7_);
		dos = _tmp9_;
		_tmp10_ = dos;
		g_data_output_stream_put_string (_tmp10_, "this is the first line\n", NULL, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_object_unref0 (dos);
			_g_object_unref0 (file);
			goto __catch0_g_error;
		}
		_tmp11_ = g_strdup ("this is the second line\n");
		text = _tmp11_;
		_tmp12_ = text;
		_tmp13_ = string_get_data (_tmp12_, &_tmp13__length1);
		_tmp14_ = _tmp13_;
		_tmp14__length1 = _tmp13__length1;
		_tmp15_ = (_tmp14_ != NULL) ? _vala_array_dup1 (_tmp14_, _tmp14__length1) : ((gpointer) _tmp14_);
		_tmp15__length1 = _tmp14__length1;
		data = _tmp15_;
		data_length1 = _tmp15__length1;
		_data_size_ = data_length1;
		written = (glong) 0;
		while (TRUE) {
			glong _tmp16_;
			guint8* _tmp17_;
			gint _tmp17__length1;
			GDataOutputStream* _tmp18_;
			guint8* _tmp19_;
			gint _tmp19__length1;
			glong _tmp20_;
			guint8* _tmp21_;
			gint _tmp21__length1;
			gssize _tmp22_ = 0L;
			gssize _tmp23_;
			glong _tmp24_;
			_tmp16_ = written;
			_tmp17_ = data;
			_tmp17__length1 = data_length1;
			if (!(_tmp16_ < ((glong) _tmp17__length1))) {
				break;
			}
			_tmp18_ = dos;
			_tmp19_ = data;
			_tmp19__length1 = data_length1;
			_tmp20_ = written;
			_tmp21_ = data;
			_tmp21__length1 = data_length1;
			_tmp22_ = g_output_stream_write ((GOutputStream*) _tmp18_, _tmp19_ + _tmp20_, (gsize) (_tmp21__length1 - _tmp20_), NULL, &_inner_error_);
			_tmp23_ = _tmp22_;
			if (_inner_error_ != NULL) {
				data = (g_free (data), NULL);
				_g_free0 (text);
				_g_object_unref0 (dos);
				_g_object_unref0 (file);
				goto __catch0_g_error;
			}
			_tmp24_ = written;
			written = _tmp24_ + _tmp23_;
		}
		data = (g_free (data), NULL);
		_g_free0 (text);
		_g_object_unref0 (dos);
		_g_object_unref0 (file);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp25_;
		GError* _tmp26_;
		const gchar* _tmp27_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp25_ = stderr;
		_tmp26_ = e;
		_tmp27_ = _tmp26_->message;
		fprintf (_tmp25_, "%s\n", _tmp27_);
		result = 1;
		_g_error_free0 (e);
		return result;
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	result = 0;
	return result;
}



