require "colorize"
require "vala"

VALA_DIR = "c:/vala-0.20.1"
VALA_VAPI_DIR = "c:/ProgramData/vala-0.20/vapi"

PNAME = {
  hello: "hello-world"
}

vala = Vala.new(
  application_type: "desktop",
  project_name: PNAME[:hello],
  pkgs: "System VGF.System gtk+-3.0",
  files: FileList["./**/*.vala"]
)

task :compile do |task_name|
  Vala.profile_task(PNAME[:hello], task_name.to_s) {
    system Vala.compile_s
  }
end

task :clean do |task_name|
  Vala.profile_task(PNAME[:hello], task_name.to_s) {
    rm_f FileList["build/**/*.*"]
  }
end

task :install do |task_name| 
  Vala.profile_task(PNAME[:hello], task_name.to_s) {
    vala.install_dependence
    # Vala.install_dep """
    #   glib
    #   gtk
    #   System
    # """
  }
end

task :hello => ["compile"]

task :default => ["compile"]
