require "colorize"
require "vala"

VALA_DIR = "c:/vala-0.20.1"
VALA_VAPI_DIR = "c:/ProgramData/vala-0.20/vapi"

PNAME = {
  hello: "hello-world"
}

task :compile do |task_name| 
  Vala.profile_task(PNAME[:hello], task_name.to_s) {
    system Vala.new(
      project_name: PNAME[:hello],
      pkgs: "System VGF.System",
      files: FileList["./**/*.vala"]
    ).compile_s
  }
end

task :clean do |task_name|
  Vala.profile_task(PNAME[:hello], task_name.to_s) {
    rm_f FileList["build/**/*.*"]
  }
end

task :install do |task_name| 
  Vala.profile_task(PNAME[:hello], task_name.to_s) {
    """
      libglib-2.0-0.dll 
      libgobject-2.0-0.dll 
      System.dll 
      VGF.System.dll
    """.split(" ").each { |x| cp "#{VALA_DIR}/bin/#{x}", "build/#{x}" }
  }
end

task :hello => ["compile"]

task :default => ["compile"]
